[build]
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NEXT_DISABLE_TURBOPACK = "1"
  NEXT_PUBLIC_SANITY_PROJECT_ID = "4o80zeix"
  NEXT_PUBLIC_SANITY_DATASET = "production"
